In [2]:
%load_ext autoreload
%autoreload 2
## self
import config
from preprocess import *

In [2]:
dev_path = config.DEV_MA_FILE
print(dev_path)

/work/2020-IIS-NLU-internship/MNLI/data/multinli_1.0/multinli_1.0_dev_matched.jsonl


In [3]:
tokenizer = BertTokenizer.from_pretrained(config.BERT_EMBEDDING)

In [4]:
dev_set = MNLI_CrossBERT_Dataset()

In [5]:
dev_set[0]

{'sentence1': tensor([ 101, 1996, 2047, 2916, 2024, 3835, 2438,  100]),
 'sentence2': tensor([  101,  3071,  2428,  7777,  1996, 14751,  6666,   100]),
 'gold_label': tensor(1)}

In [21]:
dev_set = MNLI_Raw_Dataset(dev_path, mode="develop")

In [34]:
processed = tokenizer([ s[config.p_field] for s in dev_set], [ s[config.h_field] for s in dev_set], padding=True, truncation="only_first")

In [36]:
processed.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [35]:
print(processed['input_ids'][:3])

[[101, 1996, 2047, 2916, 2024, 3835, 2438, 102, 3071, 2428, 7777, 1996, 14751, 6666, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2023, 2609, 2950, 1037, 2862, 1997, 2035, 2400, 4791, 1998, 1037, 3945, 3085, 7809, 1997, 2231, 3237, 4790, 1012, 102, 1996, 2231, 3237, 4790, 7431, 2006, 1996, 4037, 2024, 2025, 2583, 2000, 2022, 9022, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
print(processed['token_type_ids'][:3])

[[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [60]:
# test batch broad cast
aa = torch.tensor([[1,2,3], [2,4,6]]).reshape(1,2,3)
bb = torch.tensor([[1,2,3], [2,4,6]]).reshape(1,3,2)
                     
print(aa)
print(bb)

tensor([[[1, 2, 3],
         [2, 4, 6]]])
tensor([[[1, 2],
         [3, 2],
         [4, 6]]])


In [61]:
print(aa.size())
print(bb.size())
print(torch.matmul(aa, bb))
print(torch.matmul(aa, bb).size())

torch.Size([1, 2, 3])
torch.Size([1, 3, 2])
tensor([[[19, 24],
         [38, 48]]])
torch.Size([1, 2, 2])


In [3]:
batch_size = 5
nb_digits = 10
# Dummy input that HAS to be 2D for the scatter (you can use view(-1,1) if needed)
y = torch.LongTensor(batch_size,1).random_() % nb_digits
# One hot encoding buffer that you create out of the loop and just keep reusing
y_onehot = torch.FloatTensor(batch_size, nb_digits)

# In your for loop
y_onehot.zero_()
y_onehot.scatter_(1, y, 1)

print(y)
print(y_onehot)

tensor([[6],
        [7],
        [2],
        [3],
        [6]])
tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])


In [5]:
from train import *
trainer = CrossBERT_Trainer()
model, stats = trainer.train()

loading trainset from /work/2020-IIS-NLU-internship/MNLI/data/multinli_1.0/multinli_1.0_train.jsonl
loading devset from /work/2020-IIS-NLU-internship/MNLI/data/multinli_1.0/multinli_1.0_dev_matched.jsonl


KeyboardInterrupt: 

In [ ]:
#p = model._predict(test_batch).numpy().tolist()
p = [1,0,2,1,2,0,1,1]
p2 = [1,0,2,0,0,0,0,2]
from sklearn import metrics
print(metrics.confusion_matrix(p, p2))
print(metrics.classification_report(p2, p))
metrics.classification_report(p2, p,output_dict=True)['weighted avg']
metrics.precision_recall_fscore_support(p2, p)
metrics.precision_recall_fscore_support(p2, p, average='macro')